#!/usr/bin/perl
#    This file is part of IFMI PoolManager.
#
#    PoolManager is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.   

use warnings;
use strict;

my $login = (getpwuid $>);
die "must run as root" if ($login ne 'root');
die "no arguments" if ($ARGV[0] eq "");

require '/opt/ifmi/pm-common.pl';

my $conf = &getConfig;
my %conf = %{$conf};

my $nobamt = $conf{settings}{IGNOREBAMT};
my $currentm = $conf{settings}{current_mconf};
my $minerpath = $conf{miners}{$currentm}{mpath};

if ($ARGV[0] eq "start") { 
	my $mcheck = `ps -eo command | grep -Ec ^$minerpath`;
	if ($mcheck > 0) {
		die "another mining process is running."
	}
	if (-d "/opt/bamt/" && $nobamt eq "0") { 
		`/usr/sbin/mine start`;
		&blog("starting mining with mine start") if (defined(${$conf}{settings}{verbose}));
	} else { 
		&startCGMiner();
		&blog("starting mining with function call") if (defined(${$conf}{settings}{verbose}));
	}
}

if ($ARGV[0] eq "stop") { 
	if (-d "/opt/bamt/" && $nobamt eq "0") { 
		`/usr/sbin/mine stop`;
		&blog("stopping mining with mine stop") if (defined(${$conf}{settings}{verbose}));
	} else { 
		&stopCGMiner();
		&blog("stopping mining with function call") if (defined(${$conf}{settings}{verbose}));
	}
}

if ($ARGV[0] eq "boot") {
	my $bootcmd; 
	if (-e "/sbin/coldreboot") {
		$bootcmd = "/sbin/coldreboot"
	} else {
		$bootcmd = "/sbin/reboot"
	}
	`$bootcmd`;
	&blog("booting miner with $bootcmd") if (defined(${$conf}{settings}{verbose}));
}










