#!/usr/bin/perl
#    This file is part of IFMI PoolManager.
#
#    PoolManager is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.   

use warnings;
use strict;

my $login = (getpwuid $>);
die "must run as root" if ($login ne 'root');
die "no arguments" if ($ARGV[0] eq "");

require '/opt/ifmi/pm-common.pl';

my $conf = &getConfig;
my %conf = %{$conf};

my $nobamt = 0; 
if (defined($conf{settings}{IGNOREBAMT})) {
	$nobamt = 1;
}

my $minerpath = "/opt/miners/cgminer/cgminer";
$minerpath = $conf{settings}{cgminer_path} if (defined($conf{settings}{cgminer_path}));

if ($ARGV[0] eq "start") { 
	my $mcheck = `ps -eo command | grep -Ec ^$minerpath`;
	if ($mcheck > 0) {
		die "another mining process is running."
	}
	if (-e "/opt/bamt" && $nobamt == 0) { 
		system `/usr/sbin/mine start`;
		&blog("starting mining with mine start");
	} else { 
		&startCGMiner();
		&blog("starting mining with function call");
	}
}

if ($ARGV[0] eq "stop") { 
	if (-e "/opt/bamt" && $nobamt == 0) { 
		system `/usr/sbin/mine stop`;
		&blog("stopping mining with mine stop");
	} else { 
		&stopCGMiner();
		&blog("stopping mining with function call");
	}
}